spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  liquibase:
      enabled: true
      change-log: db/changelog/changelog-master.xml
  logging:
      level:
        root: INFO
        org.springframework.web: DEBUG
        org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
        org.springframework.web.servlet.DispatcherServlet: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
